baseURL = 'https://akayj.github.io/'
languageCode = 'zh-CN'
title = "Asking Life"
description = "胡思乱想-技术、生活、想法等"
theme = "yinyang"
DefaultContentLanguage = "cn"

# staticDir = ['assets']

[markup]
[markup.highlight]
style = "github"
noClasses = true
lineNos = true
lineNumbersInTable = true


[params]
headTitle = "Akayj's Life"
# mainSections = ["posts"]

[[params.socials]]
name = "About"
link = "/about"

[[params.socials]]
name = "Posts"
link = "/posts"

[[params.socials]]
name = "Tags"
link = "/tags"

[[params.socials]]
name = "Github"
link = "https://github.com/akayj"
