baseURL = 'https://akayj.github.io/'
languageCode = 'zh-CN'
title = "akayj的博客"
description = "akayj的个人博客， 聊聊技术经验、日常趣事等"
theme = "yinyang"


[params]
headTitle = "askingyj"
# mainSections = ["posts"]

[[params.socials]]
name = "Posts"
link = "/posts"

[[params.socials]]
name = "Github"
link = "https://github.com/akayj"

[markup]
[markup.highlight]
style = "github"
noClasses = true
lineNos = true
lineNumbersInTable = true
